module.exports = {
  sampleCustomer: {
    first_name: 'Dele',
    last_name: 'Alli',
    email: 'test-user@email.com',
    phone_number: '+4488823123231',
    password: 'admin123',
  },
  sampleAccountant: {
    first_name: 'Dele',
    last_name: 'Alli',
    email: 'test-accountant@email.com',
    phone_number: '+4484423123231',
    password: 'admin123',
    role: 'ACCOUNTANT',
  },
  sampleSupervisor: {
    first_name: 'Dele',
    last_name: 'Alli',
    email: 'test-supervisor@email.com',
    phone_number: '+4488823123231',
    password: 'admin123',
    role: 'SUPERVISOR',
  },
  sampleVisaOfficer: {
    first_name: 'Dele',
    last_name: 'Alli',
    email: 'test-visa-officer@email.com',
    phone_number: '+4488823123211',
    password: 'admin123',
    role: 'VISA_OFFICER',
  },
  sampleSuperAdmin: {
    first_name: 'Dele',
    last_name: 'Admin',
    email: 'test-admin@email.com',
    phone_number: '+44888231231',
    password: 'admin123',
    is_admin: true,
    role: 'SUPER_ADMIN',
  },
  superAdmin: {},
  supervisor: {},
};
